version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: payment
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    container_name: docker-compose-test
    build:
      context: ../
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/payment
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    networks:
      - test_network

networks:
  test_network: