spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect
        database: mysql
        show-sql: true
profiles:
    active: local
    group:
        local: logging-type-condole, logging-level-local
        dev: logging-type-file, logging-level-dev